### ISSUE TITLE
Customer can place order without providing details

### ISSUE THREAD

**Issue by LauraWalpole** [jamieTardi/pokeshop#15]
For an order to be processed correctly the customers details are required. The user should not be able to progress to the second stage of checkout (Payment details) without providing valid data in each compulsory field. Currently it is possible to place an order and make payment without providing any details for any combination of the following: 
- First name
- Last name
- Email address
- Shipping address

Possible fix: 
Make the 'Next' button inactive until each field contains valid data

Example of order placed with no shipping details:
![image](https://user-images.githubusercontent.com/64501770/173698244-ba2e6551-22c9-48ea-8025-73b60f89e420.png)

**Comment by jamieTardi** [comment]
fixed for logged in and non logged in customers.
