### ISSUE TITLE
Links on sign in form not working

### ISSUE THREAD

**Issue by LauraWalpole** [jamieTardi/pokeshop#20]
On the 'Sign In' page (https://poke-decks.io/signIn) there are three links provided:
'Don't have an account? Sign up'. When clicked this should navigate to https://poke-decks.io/register
'Go back to home page'. This should navigate to https://poke-decks.io/ when clicked
'Forgot password?'. This should allow the user to create a new password.

When clicked neither results in any action as these are not linked to the URLs above.
![SignIn](https://user-images.githubusercontent.com/64501770/173700400-0522fbc1-3729-4816-90ec-22b2a249e3cf.png)

**Comment by jamieTardi** [comment]
'Forgot password?'. This should allow the user to create a new password. This is a entirely separate story that needs creating as this is a large amount of work.

**Comment by jamieTardi** [comment]
@Girl-C0d3 you will need to create a separate issue for the forgotten password..
