### ISSUE TITLE
Calculate postage based on total cost of items 

### ISSUE THREAD

**Issue by LauraWalpole** [jamieTardi/pokeshop#3]
The total postage fee charged at checkout will be dependent on the total value of the items the customer has in their basket. The total cost is based on the items selected minus any discounts applied.

1) If the total cost of the items in my basket is less than £50 after I have applied any discount codes, I will be charged £4 in postage fees
2) If the total cost of the items in my basket is between £50 and £99.99 after I have applied any discount codes I will be charged £2.50 in postage fees
3) If the total cost of the items in my basket is equal to or above £100 after I have applied any discount codes I will receive free shipping

**Comment by jamieTardi** [comment]
Postage is now calculated based on how much the users cart adds up to and updated automatically
